@startuml
!include .\\Digimon.puml
!include .\\MyFileHelper.puml
!include .\\MyIdentify.puml
!include .\\MyInvalidIdException.puml
!include .\\MyList.puml
!include .\\MyPrimeHelper.puml
!include .\\MyQueue.puml
!include .\\Pokemon.puml
!include .\\Program.puml
!include .\\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\obj\Debug\net6.0\ConsoleApp8.AssemblyInfo.puml
!include .\\obj\Debug\net6.0\ConsoleApp8.GlobalUsings.g.puml
@enduml
