@startuml
class MyInvalidIdException {
    + MyInvalidIdException()
    + MyInvalidIdException(string)
    + MyInvalidIdException(string, Exception)
    # MyInvalidIdException(SerializationInfo, StreamingContext)
}
Exception <|-- MyInvalidIdException
@enduml
